import "@styles/globals.css";

import { Wallet } from "@components/Wallets";
import Navbar from "@components/Navbar";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Wallet>
          <Navbar />
          {children}
        </Wallet>
      </body>
    </html>
  );
}
